# DB Settings
hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
hibernate.connection.url=jdbc:mysql://localhost:3306/elite_learners?createDatabaseIfNotExist=true
hibernate.connection.username=root
hibernate.connection.password=root

# Dialect
hibernate.dialect=org.hibernate.dialect.MySQLDialect

# SQL Settings
hibernate.show_sql=true
hibernate.format_sql=true

# How the db schema is handled by hibernate
hibernate.hbm2ddl.auto=create

# Enable parameter padding
hibernate.query.in_clause_parameter_padding=true

# How hibernate manages sessions
hibernate.current_session_context_class=thread